name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Sphinx
        run: pip install -U Sphinx

      - name: Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          extensions: none
          tools: none

      - name: Generate HTML release
        run: ./build_release_html.sh

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          folder: BookHTML
          branch: gh-pages
